on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: pythonnewreg.azurecr.io
        username: ${{ secrets.acr_pythonnewreg_username }}
        password: ${{ secrets.acr_pythonnewreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t pythonnewreg.azurecr.io/pythonbootcamp01:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push pythonnewreg.azurecr.io/pythonbootcamp01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_pythonbootcamp01_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep python-bootcamp-0xxxxx | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace python-bootcamp-0xxxxx`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: python-bootcamp-0xxxxx
        container-registry-url: pythonnewreg.azurecr.io
        container-registry-username: ${{ secrets.acr_pythonnewreg_username }}
        container-registry-password: ${{ secrets.acr_pythonnewreg_password }}
        secret-name: pythonbootcadockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: python-bootcamp-0xxxxx
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          pythonnewreg.azurecr.io/pythonbootcamp01:${{ github.sha }}
        imagepullsecrets: |
          pythonbootcadockerauth
